import Head from "next/head";
import { Inter } from "@next/font/google";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

// Component Imports
import TrendingMovie from "components/Index/TrendingMovie";
import TrendingTV from "components/Index/TrendingTV";
import Carousal from "components/Index/Carousel";

export default function Home({ carousalData }: any) {
  // console.log(carousalData);
  return (
    <>
      <Head>
        <title>MovieDb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#0F172A] border-2 border-primary">
        <Carousal carousalData={carousalData} />
        <TrendingMovie />
        <TrendingTV />
      </main>
    </>
  );
}

function randomNumber(min: number, max: number) {
  return Math.floor(Math.random() * (max - min) + min);
}

export const getServerSideProps = async () => {
  const res = await fetch(
    `https://api.themoviedb.org/3/movie/top_rated?api_key=${
      process.env.NEXT_PUBLIC_API_KEY
    }&page=${randomNumber(1, 100)}`
  );
  const data = await res.json();
  const carousalData = data.results;

  return {
    props: {
      carousalData,
    },
  };
};
