import Head from "next/head";
import { Inter } from "@next/font/google";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

// Component Imports
import TrendingMovie from "components/Index/TrendingMovie";
import TrendingTV from "components/Index/TrendingTV";
import Carousal from "components/Index/Carousel";

export default function Home({ carousalData }: any) {
  // console.log(carousalData);
  return (
    <>
      <Head>
        <title>MovieDb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#0F172A] border-2 border-primary">
        <Carousal />
        <TrendingMovie />
        <TrendingTV />
      </main>
    </>
  );
}
